//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 GalleryIntelligentRebar.rc 使用
//
#define IDD_DIALOG_InsertRebarCol       2
#define IDD_DIALOG_InsertRebar          3
#define IDD_DIALOG_WallRebar            101
#define IDD_DIALOG_WallRebar_MainRebar  102
#define IDD_DIALOG_WallRebar_LapOption  103
#define IDD_DIALOG_WallRebar_EndType    104
#define IDD_DIALOG_WallRebar_AssociatedComponent 105
#define IDD_DIALOG_WallRebar_TwinBarSet 106
#define IDD_DIALOG_WallRebar_TieRebarSet 107
#define IDD_DIALOG_HoleRebar_Reinforcing 108
#define IDD_DIALOG_ACC_INFO             109
#define IDB_BITMAP1                     110
#define IDB_BITMAP2                     111
#define IDB_BITMAP3                     112
#define IDB_BITMAP4                     113
#define IDB_BITMAP5                     114
#define IDB_BITMAP6                     115
#define IDB_BITMAP7                     116
#define IDB_BITMAP8                     117
#define IDB_BITMAP9                     118
#define IDB_BITMAP10                    119
#define IDB_BITMAP11                    120
#define IDC_CHECK_REINV1                1000
#define IDC_EDIT_REINNUMV1              1001
#define IDC_EDIT_REINNUMV2              1002
#define IDB_BITMAP_HOLEREINFORCING      1003
#define IDD_DIALOG_InsertRebarMain      1004
#define IDD_DIALOG_InsertRebarWall      1005
#define IDD_DIALOG_SlabRebar            1006
#define IDD_DIALOG_SlabRebar_AssociatedComponent 1007
#define IDD_DIALOG_SlabRebar_EndType    1008
#define IDD_DIALOG_SlabRebar_LapOption  1009
#define IDD_DIALOG_WallRebar_MainRebar1 1010
#define IDD_DIALOG_SlabRebar_MainRebar  1011
#define IDD_DIALOG_SlabRebar_TieRebarSet 1012
#define IDC_TAB_InserRebar              1013
#define IDD_DIALOG_HoleRebar_Structural 1014
#define IDC_CHECK2                      1015
#define IDD_DIALOG_WallRebar_TwinBarSet2 1016
#define IDC_TAB_WallRebar               1017
#define IDC_EDIT_REINSPACINGV1          1018
#define IDC_CHECK9                      1018
#define IDC_LIST2                       1019
#define IDC_EDIT1                       1020
#define IDC_EDIT_REINSPACINGV2          1021
#define IDC_EDIT18                      1022
#define IDC_INSERT_TZCDEDIT             1022
#define IDC_EDIT15                      1023
#define IDC_AT_EDIT_RIGHTMOVE           1024
#define IDC_EDIT16                      1025
#define IDC_EDIT2                       1026
#define IDC_EDIT3                       1027
#define IDC_EDIT13                      1028
#define IDC_AT_EDIT_LEFTMOVE            1029
#define IDC_EDIT4                       1030
#define IDC_AT_EDIT_SPACINGDIS          1031
#define IDC_EDIT17                      1032
#define IDC_COMBO1                      1033
#define IDC_COMBO12                     1034
#define IDC_AT_EDIT_REBARDIAMETER       1035
#define IDC_DIRECTION                   1035
#define IDC_COMBO14                     1035
#define IDC_EDIT_REINNUMH3              1036
#define IDC_TAB_SlabRebar               1037
#define IDC_LIST1                       1038
#define IDC_EDIT_REINSPACINGH3          1039
#define IDC_LIST_LapOption              1040
#define IDC_COMBO6                      1041
#define IDC_COMBO_RebarStyle            1042
#define IDC_EDIT_REINNUMH4              1043
#define IDC_LIST_EndType                1044
#define IDC_EDIT14                      1045
#define IDC_EDIT_REINSPACINGH4          1046
#define IDC_LIST_AC                     1047
#define IDC_LIST_TwinBarSet             1048
#define IDC_BUTTON10                    1049
#define IDC_BUTTON1                     1050
#define IDC_BUTTON11                    1051
#define IDC_CHECK_1                     1052
#define IDC_AT_BUTTON_SELECTREFLINE     1053
#define IDC_CHECK_2                     1054
#define IDC_RADIO1                      1055
#define IDC_RADIO2                      1056
#define IDC_RADIO3                      1057
#define IDC_RADIO4                      1058
#define IDC_CHECK1                      1059
#define IDC_RADIO5                      1060
#define IDC_CHECK7                      1061
#define IDC_CHECK5                      1062
#define IDC_CHECK8                      1063
#define IDC_AD_CHECK_DOWNREBAR          1064
#define IDC_CHECK6                      1065
#define IDC_CHECK_REINV2                1066
#define IDC_AD_CHECK_LEFTREBAR          1067
#define IDC_RADIO6                      1068
#define IDC_AD_CHECK_RIGHTREBAR         1069
#define IDC_CHECK_REINH3                1070
#define IDC_RADIO7                      1071
#define IDC_CHECK_REINH4                1072
#define IDC_RADIO8                      1073
#define IDC_CHECK_IsTieRebar            1074
#define IDC_RADIO9                      1075
#define IDC_RADIO10                     1076
#define IDC_RADIO11                     1077
#define IDC_RADIO12                     1078
#define IDC_COMBO7                      1079
#define IDC_COMBO8                      1080
#define IDC_EDIT8                       1081
#define IDC_EDIT9                       1082
#define IDC_COMBO9                      1083
#define IDC_COMBO10                     1084
#define IDC_EDIT10                      1085
#define IDC_BUTTON2                     1086
#define IDC_RADIO13                     1087
#define IDC_BUTTON12                    1088
#define IDC_LIST_HoleReinforcing        1089
#define IDC_EDIT_ACC1                   1090
#define IDC_EDIT_MainRebarDis           1091
#define IDC_RADIO16                     1092
#define IDC_RADIO17                     1093
#define IDC_RADIO18                     1094
#define IDC_RADIO19                     1095
#define IDC_RADIO20                     1096
#define IDC_RADIO14                     1097
#define IDC_EDIT_ACC2                   1098
#define IDC_RADIO15                     1099
#define IDC_EDIT_L0Lenth                1100
#define IDC_S_LIST_AC                   1101
#define IDC_S_LIST_EndType              1102
#define IDC_S_LIST_LapOption            1103
#define IDC_S_LIST1                     1104
#define IDC_S_EDIT1                     1105
#define IDC_S_EDIT2                     1106
#define IDC_S_EDIT3                     1107
#define IDC_S_EDIT4                     1108
#define IDC_S_MHOLESIZE_EDIT            1109
#define IDC_S_HOLE_CHECK                1110
#define IDC_S_BUTTON1                   1111
#define IDC_S_EDIT5                     1112
#define IDC_S_COMBO_RebarStyle          1113
#define IDC_S_EDIT6                     1114
#define IDC_S_COMBO1                    1115
#define IDC_S_EDIT7                     1116
#define IDC_S_COMBO2                    1117
#define IDC_STATIC_RebarSpace           1118
#define IDC_STATIC_RebarSpace1          1119
#define IDC_S_CHECK1                    1120
#define IDC_STATIC_RebarSpace2          1121
#define IDC_S_RADIO1                    1122
#define IDC_S_RADIO3                    1123
#define IDC_S_RADIO5                    1124
#define IDC_S_RADIO2                    1125
#define IDC_S_RADIO4                    1126
#define IDC_EDIT5                       1127
#define IDC_MHOLESIZE_EDIT              1128
#define IDC_COMBO2                      1129
#define IDC_HOLE_CHECK                  1130
#define IDC_COMBO13                     1131
#define IDC_EDIT51                      1132
#define IDC_COMBO3                      1133
#define IDC_COMBO4                      1134
#define IDC_COMBO5                      1135
#define IDC_EDIT6                       1136
#define IDC_EDIT7                       1137
#define IDC_PICTURE_HOLERF              1138
#define IDC_COMBO11                     1139
#define IDC_EDIT_ACC3                   1140
#define IDC_STATIC_Anchoring            1141
#define IDC_PICTURE_HOLEST              1142
#define IDC_STATIC_Anchoring2           1142
#define IDC_LIST_HoleStructual          1143
#define IDC_EDIT_ACC4                   1144
#define IDC_EDIT_ACC5                   1145
#define IDD_DIALOG_ADDUNIONHOLE         1146
#define IDC_EDIT_ACC6                   1147
#define IDC_PICTURE_STRUCTUAL           1148
#define IDD_DIALOG_SlabRebar_TwinBarSet 1149
#define IDC_CHECK_STRUCTUALH3           1150
#define IDC_CHECK_STRUCTUALH4           1151
#define IDC_CHECK_STRUCTUALV1           1152
#define IDC_CHECK_STRUCTUALV2           1153
#define IDC_CHECK_STRUCTUALTWINH3       1154
#define IDC_SET_UNIONHOLE_BUTTON        1155
#define IDC_CHECK_STRUCTUALTWINH4       1156
#define IDC_LIST_AddUnionHole           1157
#define IDC_CHECK_STRUCTUALTWINV1       1158
#define IDC_EDIT_UNIONNAME              1159
#define IDC_CHECK_STRUCTUALH8           1160
#define IDC_CHECK_STRUCTUALTWINV2       1161
#define IDC_BUTTON_DISSUNION            1162
#define IDC_SET_UNIONHOLEST_BUTTON      1163
#define IDC_BUTTON_DISSUNIONST          1164
#define IDC_S_Space1                    1165
#define IDC_S1_STATIC_RebarSpace1       1166
#define IDC_STATIC_L0                   1167
#define IDB_BITMAP12                    1168
#define IDC_STATIC_L1                   1169
#define IDC_STATIC_La                   1170
#define IDC_S_LIST_TwinBarSet           1171
#define IDC_S_STATIC_RebarSpace1        1172
#define IDC_S_STATIC_RebarSpace2        1173
#define IDD_DIALOG_BeamInfo             1174
#define IDC_EDIT11                      1175
#define IDC_EDIT12                      1176
#define IDD_DIALOG_BeamDefault          1177
#define IDC_BUTTON3                     1178
#define IDC_BUTTON4                     1179
#define IDD_DIALOG_BeamVerticalRebar    1180
#define IDC_TAB1                        1181
#define IDD_DIALOG_BeamLapOptions       1182
#define IDC_BUTTON5                     1183
#define IDC_BUTTON6                     1184
#define IDD_DIALOG_BeamHoopRebar        1185
#define IDC_BUTTON9                     1186
#define IDC_BUTTON7                     1187
#define IDC_BUTTON8                     1188
#define IDD_DIALOG_BeamRebarMainDlg     1189
#define IDB_BITMAP13                    1190
#define IDD_DIALOG_ENDTYPESET           1191
#define IDC_COMBO_EndType               1192
#define IDD_DIALOG_FacesRebar           1193
#define IDC_BUTTON_Load                 1194
#define IDD_DIALOG_FacesRebar_MainRebar 1195
#define IDC_STATIC_EndTypePicture       1196
#define IDD_DIALOG_FacesRebar_EndType   1197
#define IDC_STATIC_EndType1             1198
#define IDC_EDIT_EndType1               1199
#define IDC_STATIC_EndType2             1200
#define IDC_EDIT_EndType2               1201
#define IDC_STATIC_EndType3             1202
#define IDC_EDIT_EndType3               1203
#define IDC_STATIC_EndType4             1204
#define IDC_EDIT_EndType4               1205
#define IDC_STATIC_EndType5             1206
#define IDC_EDIT_EndType5               1207
#define IDC_STATIC_EndType6             1208
#define IDC_EDIT_EndType6               1209
#define IDC_CHECK_EndType1              1210
#define IDC_COMBO_EndType2              1211
#define IDC_COMBO_EndType3              1212
#define IDC_COMBO_EndType4              1213
#define IDC_COMBO_EndType5              1214
#define IDC_CHECK_EndType2              1215
#define IDC_COMBO_EndType6              1216
#define IDC_STATIC_EndType7             1217
#define IDC_EDIT_EndType7               1218
#define IDC_CHECK_EndType3              1219
#define IDC_COMBO_EndType7              1220
#define IDC_COMBO_EndType8              1221
#define IDC_CHECK_EndType4              1222
#define IDC_STATIC_EndType8             1223
#define IDC_EDIT_EndType8               1224
#define IDC_EDIT_EndType9               1225
#define IDC_STATIC_EndType9             1226
#define IDC_CHECK_ACC1                  1227
#define IDC_CHECK3                      1228
#define IDC_CHECK4                      1229
#define IDC_CHECK_REINSECLECTALL        1230
#define IDC_CHECK10                     1230
#define IDC_CHECK_STRSELECTALL          1231
#define IDC_CHECK_ACC2                  1232
#define IDC_TAB_FacesRebar              1233
#define IDB_BITMAP14                    1234
#define IDB_BITMAP15                    1235
#define IDB_BITMAP16                    1236
#define IDB_BITMAP17                    1237
#define IDB_BITMAP18                    1238
#define IDB_BITMAP19                    1239
#define IDB_BITMAP20                    1240
#define IDB_BITMAP21                    1241
#define IDB_BITMAP22                    1242
#define IDD_DIALOG_RainshedRebar        1243
#define IDC_R_LIST1                     1244
#define IDC_R_EDIT1                     1245
#define IDC_R_EDIT2                     1246
#define IDC_R_EDIT3                     1247
#define IDC_R_EDIT4                     1248
#define IDC_EDIT_RL0Lenth               1249
#define IDD_DIALOG_Gwall                1250
#define IDC_EDIT_GPositive              1251
#define IDC_EDIT_GSide                  1252
#define IDC_EDIT_GReverse               1253
#define IDC_HOLE_GCHECK                 1254
#define IDC_MHOLESIZE_GEDIT             1255
#define IDC_EDIT_GLevel                 1256
#define IDC_LIST_GMainRebar             1257
#define IDOK_Gwall                      1258
#define IDCANCEL_Gwall                  1259
#define IDD_DIALOG_REBAREDIT            1260
#define IDC_EDIT_RMOVELENTH             1261
#define IDD_COMBINEREBAR_DIALOG         1262
#define IDC_CHECK_RFRONTDIR             1263
#define IDD_DIALOG_CoverslabRebar       1264
#define IDC_CHECK_RFRONTDIR2            1265
#define IDC_CHECK_RRotateDir            1266
#define IDC_COMBO_RTYPE                 1267
#define IDD_DIALOG_CoverslabRebar_MainRebar 1268
#define IDC_CHECK_RRotateDir2           1269
#define IDC_CHECK_RUseEnd               1270
#define IDC_BUTTON_RSELECTREBARS        1271
#define IDD_DIALOG_CoverslabRebar_TieRebarSet 1272
#define IDC_BUTTON_SELECT_VERREBAR      1273
#define IDD_DIALOG_CoverslabRebar_EndType 1274
#define IDC_CHECK_GENVREBAR             1275
#define IDD_DIALOG_CoverslabRebar_TwinBarSet 1276
#define IDC_CHECK_GENVREBAR2            1277
#define IDC_CHECK_USEINTERSECT          1278
#define IDD_DIALOG_TwinBarTool          1279
#define IDC_TAB_CoverslabRebar          1280
#define IDC_C_EDIT1                     1281
#define IDC_C_EDIT2                     1282
#define IDC_C_EDIT3                     1283
#define IDC_C_HOLE_CHECK                1284
#define IDC_C_MHOLESIZE_EDIT            1285
#define IDC_C_EDIT4                     1286
#define IDC_C_LIST1                     1287
#define IDC_C_COMBO_RebarStyle          1288
#define IDC_C_COMBO1                    1289
#define IDC_C_COMBO2                    1290
#define IDC_C_STATIC_RebarSpace1        1291
#define IDC_C_STATIC_RebarSpace2        1292
#define IDC_C_CHECK1                    1293
#define IDC_C_RADIO1                    1294
#define IDC_C_RADIO3                    1295
#define IDC_C_RADIO5                    1296
#define IDC_C_RADIO2                    1297
#define IDC_C_RADIO4                    1298
#define IDC_C_BUTTON1                   1299
#define IDC_C_LIST_TwinBarSet           1300
#define IDC_C_LIST_EndType              1301
#define IDD_DIALOG_DOORHOLE             1302
#define IDC_LIST_DoorHole               1303
#define IDC_FaceUnion_CHECK             1304
#define IDD_DIALOG_FacesRebar_Union     1305
#define IDD_AddVerticalRebar_DIALOG     1306
#define IDC_SlabUnion_CHECK             1307
#define IDC_AT_EDIT_UPMOVE              1308
#define IDC_AT_EDIT_DOWNMOVE            1309
#define IDC_AT_CHECK_ISAVESPACING       1310
#define IDD_DIALOG_HiddenBeam           1311
#define IDC_AT_BUTTON_SELECTREFREBAR    1312
#define IDC_AD_CHECK_UPREBAR            1313
#define IDD_DIALOG_TieRebarTools        1314
#define IDD_DIALOG_URebarTool           1315
#define IDD_DIALOG_StittupRebarTool     1316
#define IDD_DIALOG_Stairs               1317
#define IDD_DIALOG_DomeRebarDlg         1318
#define IDD_DIALOG_Insert               1319
#define IDD_DIALOG_DomeRoundDlg         1320
#define IDD_DIALOG_DomeMainDlg          1321
#define IDD_DIALOG_Parapet              1322
#define IDC_STATIC_WALLNAME             1323
#define IDC_STATIC_PANELNAME            1324
#define IDD_DIALOG_CustomizeRebar       1325
#define IDC_STATIC_PMaindlg             1326
#define IDC_EDIT_PUlenth                1327
#define IDD_DIALOG_BaseRebar            1328
#define IDD_DIALOG_REBARLINK            1329
#define IDC_STATIC_1                    1330
#define IDC_STATIC_SlabRebarMehod       1331
#define IDD_DIALOG_UTOSTIRRUP           1332
#define IDD_DIALOG_DomeDetail           1333
#define IDC_RBUTTON_ROTATE              1334
#define IDC_REDIT                       1335
#define IDC_SeismicGrade                1335
#define IDC_EDIT_RRotate                1336
#define IDD_DIALOG_AnchorinModify       1337
#define IDD_DIALOG_CustomizeRebar1      1338
#define IDD_DIALOG_CNWallRebar_TwinBarSet 1339
#define IDC_EDIT_JC1                    1340
#define IDD_DIALOG1                     1341
#define IDC_COMBO1_1                    1342
#define IDC_COMBO2_1                    1343
#define IDC_COMBO3_1                    1344
#define IDC_EDIT1_1                     1345
#define IDC_LIST3                       1346
#define IDD_DIALOG_CNWallRebar_TieRebarSet 1347
#define IDD_DIALOG_CNWallRebar_MainRebar 1348
#define IDD_DIALOG_CNWallRebar_EndType  1349
#define IDD_DIALOG_CNWallRebar_AssociatedComponent 1350
#define IDD_DIALOG_CNWallRebar          1351
#define IDD_DIALOG_CNWallRebar_LapOption 1352
#define IDD_DIALOG_CNACC_INFO           1353
#define IDD_DIALOG_CNGwall              1354
#define IDD_DIALOG_CNCutRebarDlg        1355
#define IDD_DIALOG_RebarConnect         1356
#define IDC_COMBO_ConnectType           1357
#define IDC_CHECK_CrossConnect          1358
#define IDC_EDIT_CrossLength            1360
#define IDC_BUTTON_CrossChange          1361
#define IDC_BUTTON_SelectCrossPos       1362
#define IDC_BUTTON_RebarConnectPreView  1363
#define IDD_DIALOG_STRETCHSTIRRUPREBAR  1366
#define IDC_EDIT                        1368
#define IDD_DIALOG_ShowHideRebarByDia   1368
#define IDCHOOSEEDITLINE                1369
#define IDPREVIEW                       1370
#define IDC_COMBO_DIA                   1370
#define IDD_DIALOG_ModifyRebarTool      1370
#define IDC_COMBO_SHOWHIDE              1371
#define IDC_COMBO_RABARDIA              1372
#define IDD_DIALOG_SetXml               1372
#define IDC_THICKNESS                   1373
#define IDC_COMBO_CONNECTSTYLE          1374
#define IDD_DIALOG_BreakEllipseWall     1374
#define IDC_COMBO_Level                 1375
#define IDC_COMBO_Grade                 1375
#define IDC_COMBO_Diameter              1376
#define IDD_DIALOG_Gallery_Settings     1376
#define IDC_EDIT_Space                  1377
#define IDD_DIALOG_Gallery_Settings_MainRebar_Page 1377
#define IDC_BUTTON_Preview              1378
#define IDD_DIALOG_Gallery_Settings_EndType_Page 1378
#define IDC_BUTTON_Select               1379
#define IDC_EDIT_SPACING                1379
#define IDC_CHECK_OverrideTail          1380
#define IDC_EDIT_ZDYLEVEL               1380
#define IDD_DIALOG_SetLaeAndLa0         1380
#define IDC_EDIT_SPACING2               1381
#define IDC_EDIT_ZDYTYPE                1381
#define IDC_COMBO_XmlFileName           1381
#define IDC_CHECK_INNER                 1382
#define IDD_SetLae                      1382
#define IDC_BUTTON_BreakEllipseWall     1383
#define IDC_EDIT_BreakNum               1384
#define IDD_SetLa0                      1384
#define IDC_LIST_BreakInfo              1385
#define IDC_SELECT_MODEL                1386
#define IDC_TAB_La                      1387
#define IDC_SELECT_MODEL2               1387
#define IDC_RebarGrade                  1390
#define IDD_DIALOG_EdgeRebar            1390
#define IDC_RebarDiameter               1391
#define IDD_DIALOG_RebarTemplate        1392
#define IDC_OverlapArea                 1393
#define IDC_ConcreteGrade               1394
#define IDD_DIALOG_TieRebarFace         1395
#define IDD_DIALOG_Combine_Setting      1395
#define IDD_DIALOG_Combine_Setting_MainRebar 1396
#define IDC_template                    1397
#define IDC_RebarTemplate               1398
#define IDD_DIALOG_TieRebarFace1        1400
#define IDC_SaveTemplate                1401
#define IDC_EDIT_TemplateName           1405
#define IDC_DeleteTemplate              1407
#define IDC_UpdataDlg                   1408
#define IDC_STATIC_Prompt               1409
#define IDC_STATIC1                     1410
#define IDC_STATIC2                     1411
#define IDC_STATIC3                     1412
#define IDC_EDIT_HNum                   1413
#define IDC_EDIT_VNum                   1414
#define IDC_COMBO_TieDiameter           1416
#define IDB_BITMAP23                    1417
#define IDB_BITMAP24                    1418
#define IDB_BITMAP_GalleryRebar         1418
#define IDD_DIALOG_Catchpit_MainRebar   1419
#define IDC_TAB_FacesRebarEx            1419
#define IDD_DIALOG_CatchpitRebar        1420
#define IDC_EDIT_Side                   1420
#define IDD_DIALOG_FacesRebarEx         1421
#define IDC_EDIT_Front                  1421
#define IDD_DIALOG_FacesRebar_MainRebarEx 1422
#define IDC_EDIT_HSpacing               1422
#define IDD_DIALOG_CircleAndSquare      1423
#define IDC_EDIT_PSpacing               1423
#define IDC_EDIT_CSpacing               1424
#define IDC_EDIT_PAngle                 1425
#define IDC_COMBO_HDiameter             1426
#define IDC_COMBO_HGrade                1427
#define IDC_COMBO_CDiameter             1428
#define IDC_COMBO_CGrade                1429

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1425
#define _APS_NEXT_COMMAND_VALUE         1365
#define _APS_NEXT_CONTROL_VALUE         1430
#define _APS_NEXT_SYMED_VALUE           1367
#endif
#endif
